name: Build and SonarCloud analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        env:
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run:  mvn -B verify sonar:sonar -Dsonar.projectKey=Pluhs_bala_2sm-soen341projectW2024 -Dsonar.organization=pluhs -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
